export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';


export const FETCH_INTERNSHIPS_SUCCESS = 'FETCH_INTERNSHIPS_SUCCESS';
export const CREATE_INTERNSHIP_SUCCESS = 'CREATE_INTERNSHIP_SUCCESS';
export const UPDATE_INTERNSHIP_SUCCESS = 'UPDATE_INTERNSHIP_SUCCESS';
export const DELETE_INTERNSHIP_SUCCESS = 'DELETE_INTERNSHIP_SUCCESS';

export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_RESUME_SUCCESS = 'FETCH_RESUME_SUCCESS';
export const CREATE_RESUME_SUCCESS = 'CREATE_RESUME_SUCCESS';
export const UPDATE_RESUME_SUCCESS = 'UPDATE_RESUME_SUCCESS';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';

